language: java
sudo: false

services:
- docker

env:
  - TANGO_HOST=localhost:10000

#skip mvn install
install: /bin/true

script:
  - docker-compose up -d
  #TODO wait-for-it
  - sleep 30
  - docker ps
  - mvn clean install -Ptravis
jdk:
  - openjdk8
  - openjdk7
cache:
  directories:
    - '$HOME/.m2/repository'


jobs:
  include:
    - stage: deploy
      name: "Deploy to SonarCloud"
      jdk: openjdk8
      install: mvn clean install -Ptravis
      script:
        - mvn sonar:sonar -Ptravis
      addons:
        sonarcloud:
          organization: "tango-controls"
          token:
            secure: $SONAR_TOKEN
    -
      name: "Deploy to Codacy"
      jdk: openjdk8
      install: mvn clean install -Ptravis
      script:
        - mvn com.gavinmogan:codacy-maven-plugin:coverage -Ptravis
    -
      name: "Deploy to Codcov.io"
      jdk: openjdk8
      install: mvn clean install -Ptravis
      script:
        - bash <(curl -s https://codecov.io/bash)
    -
      name: "Deploy artifacts"
      jdk: openjdk8
      script:
       - cd parent
       - mvn versions:set versions:update-child-modules -DnewVersion=${TRAVIS_BRANCH} -DprocessAllModule
       - mvn install -Dmaven.test.skip=true
      before_deploy: cp .travis/settings.xml $HOME/.m2/settings.xml
      after_deploy:
        - cd parent
        - mvn versions:set versions:update-child-modules -DprocessAllModules -DnextSnapshot
        - .travis/push.sh
      deploy:
        - provider: script
          script: mvn deploy -Dmaven.test.skip=true
          skip_cleanup: true
          on:
            tags: true
        - provider: releases
          file: assembly/target/JTango-${TRAVIS_TAG}.jar
          api_key: $GITHUB_TOKEN
          skip_cleanup: true
          on:
            tags: true
