language: java
sudo: false

services:
- docker

env:
  - TANGO_HOST=localhost:10000

before_script:
  - docker-compose up -d
  #TODO wait-for-it
  - sleep 30
  - docker ps

#skip mvn install
install: /bin/true

script:
  - mvn clean install -Ptravis
jdk:
  - openjdk8
  - openjdk7
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn sonar:sonar -Ptravis
  - mvn com.gavinmogan:codacy-maven-plugin:coverage -Ptravis
addons:
  sonarcloud:
    organization: "tango-controls"
    token:
      secure: $SONAR_TOKEN
cache:
  directories:
    - '$HOME/.m2/repository'

jobs:
  include:
    - stage: deploy
      jdk: openjdk8
      script:
       - cd parent
       - mvn versions:set versions:update-child-modules -DnewVersion=${TRAVIS_BRANCH} -DprocessAllModule
       - mvn install -Dmaven.test.skip=true
      before_deploy: cp .travis/settings.xml $HOME/.m2/settings.xml
      after_deploy:
        - cd parent
        - mvn versions:set versions:update-child-modules -DprocessAllModules -DnextSnapshot
        - .travis/push.sh
      deploy:
        - provider: script
          script: mvn deploy -Dmaven.test.skip=true
          skip_cleanup: true
          on:
            tags: true
        - provider: releases
          file: assembly/target/JTango-${TRAVIS_TAG}.jar
          api_key: $GITHUB_TOKEN
          skip_cleanup: true
          on:
            tags: true
