version: '3.7'
services:
  tango-db:
    image: tangocs/mysql:9.2.2
    ports:
      - "9999:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - default
  tango-cs:
    image: tangocs/tango-cs:9
    ports:
      - "10000:10000"
    environment:
      - TANGO_HOST=localhost:10000
      - MYSQL_HOST=tango-db:3306
      - MYSQL_USER=tango
      - MYSQL_PASSWORD=tango
      - MYSQL_DATABASE=tango
    links:
      - "tango-db:localhost"
    depends_on:
      - tango-db
    networks:
      - default
  tango-jive:
    image: tangocs/tango-jive:latest
    depends_on:
      - tango-cs
    environment:
      - TANGO_HOST=tango-cs:10000
      #FIXME
      - DISPLAY=${YOUR_WORKSTATION_IP_ADDRESS}:0.0
    networks:
      - default

networks:
  default:
    driver: bridge
